= Attributes
:source-highlighter: rouge
:imagesdir: images

[.lead]
Instructions to customise the layout of Graphviz nodes, edges, graphs,
subgraphs, and clusters.

* The table below describes the attributes used by various Graphviz tools.
* The table gives the name of the attribute, the graph components (node, edge,
  etc.) which use the attribute and the type of the attribute (strings
  representing legal values of that type).
* Where applicable, the table also gives a default value for the attribute, a
  minimum allowed setting for numeric attributes, and certain restrictions on
  the use of the attribute.

'''

* Note that attribute names are case-sensitive.
* This is usually true for attribute values as well, unless noted.

'''

* All Graphviz attributes are specified by name-value pairs.
* Thus, to set the color of a node `abc`, one would use
+
[source,dot]
digraph {
  abc [color = red]
}
+
[graphviz,target=color]
....
digraph {
  abc [color = red]
}
....

* Similarly, to set the arrowhead style of an edge `abc \-> def`, one would use:
+ 
[source,dot]
digraph {
  abc -> def [arrowhead = diamond]
}
+
[graphviz,target=arrowhead]
....
digraph {
  abc -> def [arrowhead = diamond]
}
....

* Further details concerning the setting of attributes can be found in the
  description of the DOT language.

'''

* At present, most device-independent units are either inches or points, which
  we take as 72 points per inch.

'''

[NOTE]
====
* Some attributes, such as `dir` or `arrowtail`, are ambiguous when used in DOT
  with an undirected graph since the head and tail of an edge are meaningless.
* As a convention, the first time an undirected edge appears, the DOT parser
  will assign the left node as the tail node and the right node as the head.
* For example, the edge `A -- B` will have tail A and head B.
* It is the user's responsibility to handle such edges consistently.
* If the edge appears later, in the format
+
[source,dot]
graph {
  B -- A [taillabel = "tail"]
}

** the drawing will attach the tail label to node `A`.
* To avoid possible confusion when such attributes are required, the user is
  encouraged to use a directed graph.
* If it is important to make the graph appear undirected, this can be done using
  the `dir`, `arrowtail` or `arrowhead` attributes.
====

* The tools accept standard C representations for `int` and `double` types.
* For the `bool` type, TRUE values are represented by `true or `yes`
  (case-insensitive) and any non-zero integer, and FALSE values by `false` or
  `no` (case-insensitive) and zero.
* In addition, there are a variety of specialized types such as `arrowType`,
  `color`, `point` and `rankdir`.
* Legal values for these types are given at the end.

'''

* The *Used By* column field indicates which graph component(s) the attribute
  applies to.

'''

* In the *Notes* field, an annotation of _write only_ indicates that the attribute
  is used for output, and is not used or read by any of the layout programs.

[%header%autowidth,cols=6]
|===
|Name	|Used By		|Type		|Default	|Minimum
|Description, notes

|<<label>>
|Edges, Nodes, Graphs, Clusters	|lblString
|`"\N"` (nodes) `""` (otherwise)				|
|
|===

[#label]
== label

[.lead]
Text label attached to objects

* type: _lblString, default: `"\N"` (nodes) , `""` (otherwise)_

'''

* If a node's shape is record, then the label can have a special format which
  describes the record layout.

'''

* Note that a node's default label is `"\N"`, so the node's name or ID becomes its
  label.

'''

* Technically, a node's name can be an HTML string but this will not mean that
  the node's label will be interpreted as an HTML-like label.
* This is because the node's actual label is an ordinary string, which will be
  replaced by the raw bytes stored in the node's name.

'''

* To get an HTML-like label, the label attribute value itself must be an HTML
  string.

.Example: Van Gogh Paintings
--
[source,dot]
----
graph {
  label="Vincent van Gogh Paintings"

  subgraph cluster_self_portraits {
    label="Self-portraits"

    spwgfh [label="Self-Portrait with Grey Felt Hat"]
    spaap [label="Self-Portrait as a Painter"]
  }
  
  subgraph cluster_flowers {
    label="Flowers"

    sf [label="Sunflowers"]
    ab [label="Almond Blossom"]
  }
}
----

[graphviz,target=van-gogh-paintings]
....
graph {
  label="Vincent van Gogh Paintings"

  subgraph cluster_self_portraits {
    label="Self-portraits"

    spwgfh [label="Self-Portrait with Grey Felt Hat"]
    spaap [label="Self-Portrait as a Painter"]
  }
  
  subgraph cluster_flowers {
    label="Flowers"

    sf [label="Sunflowers"]
    ab [label="Almond Blossom"]
  }
}
....
--

* Valid on:
** Edges
** Nodes
** Graphs
** Clusters
